-- SELECCIONANDO LA BASE DE DATOS JARVIS
use jarvis;

-- CREANDO LA TABLA AFD_CLIENTES
CREATE TABLE AFD_CLIENTES (
    ID INT AUTO_INCREMENT AUTO_INCREMENT KEY,
    NOMBRE varchar(25),
    PAIS varchar(25),
    CATEGORIA varchar(30),
    NUM_VENTA int
);

-- MODIFICANDO LA TABLA AFD_CLIENTES
-- AGREGANDO LA COLUMNA TELEFONO
ALTER TABLE AFD_CLIENTES ADD TELEFONO INT;
-- AGREGANDO LA COLUMNA BORRADO
ALTER TABLE AFD_CLIENTES ADD BORRADO BOOLEAN;

-- MODIFICANDO LA TABLA AFD_CLIENTES, ELIMINANDO LA COLUMNA NUM_VENTA
ALTER TABLE AFD_CLIENTES DROP NUM_VENTA;

-- MODIFICANDO LA TABLA AFD_CLIENTES, MODIFICANDO LA COLUMNA TELEFONO
ALTER TABLE AFD_CLIENTES MODIFY COLUMN TELEFONO VARCHAR(15);

-- ELIMINANDO LA TABLA AFDTMP
DROP TABLE AFDTMP;
DROP TABLE AFD_CLIENTES;



-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- AGREGANDO DATOS
INSERT INTO AFD_CLIENTES (NOMBRE, PAIS, CATEGORIA, TELEFONO, BORRADO) VALUES ('Nelson Cortes','CHILE','PREMIUM','+56934528534',FALSE);
INSERT INTO AFD_CLIENTES (NOMBRE, PAIS, CATEGORIA, TELEFONO, BORRADO) VALUES ('Sebastián Retamal','CHILE','GOLDEN','+56936793265',FALSE);

-- ACTUALIZANDO DATO
UPDATE AFD_CLIENTES SET BORRADO = FALSE;

-- ACTUALIZANDO CON CONDICION
UPDATE AFD_CLIENTES SET BORRADO = TRUE WHERE NOMBRE LIKE '%SEBA%';
UPDATE AFD_CLIENTES SET BORRADO = FALSE, PAIS = 'AUSTRALIA', CATEGORIA = 'BLACK' WHERE NOMBRE LIKE '%SEBA%';

-- CONSULTANDO TODOS LOS DATOS
SELECT * FROM AFD_CLIENTES;

-- CONSULTANDO DATOS CON CONDICIONES
SELECT *
FROM AFD_CLIENTES
WHERE NOMBRE = 'Sebastián Retamal';

SELECT *
FROM AFD_CLIENTES
WHERE NOMBRE LIKE '%SEBA%';


-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- REVISANDO LA TABLA CLIENTES
SELECT * FROM CLIENTES;

-- UPDATE
UPDATE CLIENTES
SET CATEGORIA = 'Eco'
WHERE ID = 6;

-- MAX
SELECT MAX(NUM_VENTA)
FROM CLIENTES;

-- MAX CON CONSULTA ANIDADA
SELECT *
FROM CLIENTES
WHERE NUM_VENTA = (
    SELECT MAX(NUM_VENTA)
    FROM CLIENTES
    );

-- MAX SELECCIONANDO LOS CAMPOS A MOSTRAR
SELECT CATEGORIA, NOMBRE
FROM CLIENTES
WHERE NUM_VENTA = (
    SELECT MAX(NUM_VENTA)
    FROM CLIENTES
    );

-- MIN
SELECT MIN(NUM_VENTA)
FROM CLIENTES;

-- REVISANDO EL DATO CON REL VALOR OBTENIDO DEL MIN()
SELECT *
FROM CLIENTES
WHERE NUM_VENTA = 3;

-- CONSULTA ANIDADA PARA OPTENER QUIEN TIENE EL MIN
SELECT *
FROM CLIENTES
WHERE NUM_VENTA = (
    SELECT MIN(NUM_VENTA)
    FROM CLIENTES
    );

-- COUNT
SELECT COUNT(*)
FROM CLIENTES;

-- COUNT CON SELECT ANIDADO
SELECT COUNT(*)
FROM CLIENTES
WHERE NUM_VENTA = (
    SELECT MIN(NUM_VENTA)
    FROM CLIENTES
    );

-- COUNT CON NUMERO DE VENTAS IGUAL A 9
SELECT COUNT(*)
FROM CLIENTES
WHERE NUM_VENTA = 9;

-- COUNT CON NUMERO DE VENTAS MAYORES A 6
SELECT COUNT(*)
FROM CLIENTES
WHERE NUM_VENTA > 6;


-- COUNT CON NUMERO DE VENTAS DISTINTAS A 6
SELECT COUNT(*)
FROM CLIENTES
WHERE NUM_VENTA <> 9;

-- AVG (PROMEDIO)
SELECT AVG(NUM_VENTA)
FROM CLIENTES;

-- AVG DE VENTAS MAYORES E IGUALES A 4
SELECT AVG(NUM_VENTA)
FROM CLIENTES
WHERE NUM_VENTA >= 4;

-- SUM (SUMA)
SELECT SUM(NUM_VENTA)
FROM CLIENTES;

-- SUMA DE LOS NUMEROS DE VENTA QUE TIENEN NUMEROS DE VENTA
-- MENORES IGUALES A 4
SELECT SUM(NUM_VENTA)
FROM CLIENTES
WHERE NUM_VENTA <= 4;

-- ****
-- ORDER BY ASC (ORDEN ASCENDENTE)
SELECT *
FROM CLIENTES
ORDER BY NOMBRE ASC ;

-- ODER BY DESC (ORDEN DESCENTE)
SELECT *
FROM CLIENTES
ORDER BY NOMBRE DESC ;

-- DESCRIBE (OBTENIENDO NOMBRE DE COLUMNAS)
DESCRIBE CLIENTES;
SHOW COLUMNS FROM CLIENTES;

-- ****

-- LIKE (PARECIDO)
SELECT *
FROM CLIENTES
WHERE PAIS LIKE 'C%';

-- NO MOSTRAR LOS REPETIDOS
SELECT DISTINCT(PAIS)
FROM CLIENTES
WHERE PAIS LIKE 'C%';

-- LIKE DE TERMINADOS EN A CON DISTINCT
SELECT DISTINCT (PAIS)
FROM CLIENTES
WHERE PAIS LIKE '%A';

-- INSERT
INSERT CLIENTES (NOMBRE, PAIS, CATEGORIA, NUM_VENTA) VALUES ('Camila Carrasco Latin', 'Brasil', 'M', 15)

-- LIKE CON CONDICIONAL DE NUMERO DE CARACTERES MINIMOS
SELECT *
FROM CLIENTES
WHERE CATEGORIA LIKE 'M_%';

-- LIKE CON INICIO Y TERMINO DEL REGISTRO
SELECT *
FROM CLIENTES
WHERE NOMBRE LIKE 'A%S';

-- IN
SELECT *
FROM CLIENTES
WHERE PAIS IN ('Alemania','China','España','Italia');

-- IN CON SELECT ANIDADO CON WHERE LIKE
SELECT *
FROM CLIENTES
WHERE PAIS IN (
    SELECT DISTINCT(PAIS)
    FROM CLIENTES
    WHERE PAIS LIKE '%A'
    );

-- BETWEEN
SELECT *
FROM CLIENTES
WHERE NUM_VENTA BETWEEN 5 AND 7;

-- AND (AGREGANDO MAS CONDICIONES)
SELECT *
FROM CLIENTES
WHERE NUM_VENTA BETWEEN 5 AND 7
AND PAIS = 'China';

-- ALIAS para Columna
SELECT DISTINCT(PAIS) AS COUNTRIES
FROM CLIENTES
WHERE PAIS LIKE '%A';

-- ALIAS para Tablas
SELECT DISTINCT(CLI.PAIS)
FROM CLIENTES AS CLI
WHERE PAIS LIKE '%A';



-- INSER A COMPRAS
INSERT COMPRAS (ID, NUMERO_ORDEN, CLIENTE_ID) VALUES (1, 2782872,1);
INSERT COMPRAS (ID, NUMERO_ORDEN, CLIENTE_ID) VALUES (2, 2782873,3);
INSERT COMPRAS (ID, NUMERO_ORDEN, CLIENTE_ID) VALUES (3, 2782874,4);
INSERT COMPRAS (ID, NUMERO_ORDEN, CLIENTE_ID) VALUES (4, 2782875,1);

-- CONSULTANDO COMPRAS
SELECT * FROM COMPRAS;

-- INNER JOIN
SELECT *
FROM CLIENTES AS CLI
INNER JOIN COMPRAS AS COM ON CLI.ID = COM.CLIENTE_ID
WHERE CLI.PAIS = 'Chile';

-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  Clase 3 de SQL   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

USE jarvis;

-- INNER JOIN
SELECT *
FROM PRODUCTOS AS PRO
INNER JOIN TIPO_PRODUCTO AS TPR ON PRO.TIPO_PRODUCTO_ID = TPR.ID;

-- ¿Cuantos clientes repetidos tengo?
-- R:
SELECT *
FROM (SELECT NOMBRE, COUNT(*) as CONTEO
FROM CLIENTES
group by NOMBRE) C
WHERE C.CONTEO > 1;

-- Contando clientes
SELECT COUNT(*)
FROM CLIENTES;

-- Contando clientes únicos
SELECT COUNT(DISTINCT(NOMBRE))
FROM CLIENTES;

-- LEFT JOIN
SELECT *
FROM CLIENTES CLI
LEFT JOIN COMPRAS COM ON CLI.ID = COM.CLIENTE_ID
WHERE COM.ID IS NULL;

-- FULL OUTER JOIN
SELECT *
FROM CLIENTES CLI
LEFT JOIN COMPRAS C on CLI.ID = C.CLIENTE_ID
LEFT JOIN DETALLE_COMPRA D on C.ID = D.COMPRA_ID
LEFT JOIN PRODUCTOS P2 on D.PRODUCTO_ID = P2.ID
UNION ALL
SELECT *
FROM CLIENTES
INNER JOIN COMPRAS C2 on CLIENTES.ID = C2.CLIENTE_ID
INNER JOIN DETALLE_COMPRA DC on C2.ID = DC.COMPRA_ID
RIGHT JOIN PRODUCTOS P on P.ID = DC.PRODUCTO_ID;





-- DIFERENCE OF FULL OUTER JOIN
SELECT *
FROM CLIENTES CLI
LEFT JOIN COMPRAS C on CLI.ID = C.CLIENTE_ID
LEFT JOIN DETALLE_COMPRA D on C.ID = D.COMPRA_ID
LEFT JOIN PRODUCTOS P2 on D.PRODUCTO_ID = P2.ID
WHERE C.ID IS NULL
UNION ALL
SELECT *
FROM CLIENTES
INNER JOIN COMPRAS C2 on CLIENTES.ID = C2.CLIENTE_ID
INNER JOIN DETALLE_COMPRA DC on C2.ID = DC.COMPRA_ID
RIGHT JOIN PRODUCTOS P on P.ID = DC.PRODUCTO_ID
WHERE C2.ID IS NULL;


-- GROUP BY
SELECT COUNT(*) AS 'Q_PAISES', PAIS
FROM CLIENTES
GROUP BY PAIS
ORDER BY Q_PAISES DESC;

SELECT * FROM CLIENTES;


-- Crear tabla desde una query
CREATE TABLE jarvis.AFDTMP
AS (
    SELECT COUNT(*) AS 'Q_PAISES', PAIS
    FROM CLIENTES
    GROUP BY PAIS
    ORDER BY Q_PAISES DESC
);

-- consultando tabla
select * from AFDTMP;

-- Eliminando tabla
drop table AFDTMP;


-- Creando una vista
CREATE VIEW VIEW_CLIENTES
AS SELECT *
FROM CLIENTES
WHERE PAIS LIKE 'C%';

-- consultando la vista
select * from VIEW_CLIENTES;

-- eliminando la vista
drop view VIEW_CLIENTES;